shop/urls.py
from django.conf.urls.static import static
from django.urls import path

from wb_shop_root import settings
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductsHome.as_view(), name='index'),
    path('search', views.SearchProducts.as_view(), name='search_products'),
    path('<slug:product_slug>', views.SingleProduct.as_view(), name='single_product'),
    path('<slug:product_slug>/add_review', views.AddReview.as_view(), name='add_review'),
    path('categories/<slug:category_slug>', views.ProductsInCategory.as_view(), name='single_category')

]

# TODO: Перенести в urls.py -> wb_shop_root
handler404 = views.page_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wb_shop_root/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    # TODO: Здесь лучше сделать так, чтобы в
    #  конце урла можно было не указывать слэш
    re_path(r'^admin/?', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

shop/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from pytils.translit import slugify
from django.core.validators import ValidationError, MinValueValidator
from users.models import User

from my_utils.utils import validate_image, get_file_path
from shop.validators import ProductTitleValidator, ProfileImageValidator


class Category(models.Model):
    title = models.CharField(
        _('Название'),
        max_length=255,
        unique=True
    )
    slug = models.SlugField(max_length=50)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(
        'Название',
        max_length=255,
        unique=True,
        validators=[ProductTitleValidator()]
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        null=False
    )
    description = models.TextField(
        'Описание товара', max_length=600
    )
    price = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    sale_price = models.PositiveIntegerField(blank=True, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='products'
    )
    image = models.ImageField(
        'Фото',
        upload_to=get_file_path,
        default='shop/default.jpg',
        #     validators=[
        #         validate_image, ProfileImageValidator()
        #         ]
        # )
        validators=[validate_image]
    )
    is_available = models.BooleanField(default=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('-is_available', '-time_update')

    def clean(self):
        if self.sale_price and self.sale_price >= self.price:
            raise ValidationError(
                f'Цена со скидкой не может быть больше либо равна '
                f'{self.price} руб.'
            )
        return super().clean()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Banner(models.Model):
    title = models.CharField(
        'Наименование баннера',
        max_length=255,
    )
    image = models.ImageField(
        'Баннер категории',
        upload_to=get_file_path,
        default='shop/default.jpg'
    )
    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        related_name='banners'
    )

    class Meta:
        verbose_name = 'Баннер'
        verbose_name_plural = 'Баннеры'

    def save(self, *args, **kwargs):
        self.title = f'Баннер {self.category} {self.pk}'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Review(models.Model):
    STARS_GOODS = (
        (1, '1-Отвратительно'),
        (2, '2-Плохо'),
        (3, '3-Удовлетворительно'),
        (4, '4-Хорошо'),
        (5, '5-Отлично'),
    )
    # TODO сделать отдельную модель grade - оценка

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField('Ваш отзыв', blank=True)
    stars = models.IntegerField('Ваша оценка', choices=STARS_GOODS)
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return f'{self.stars}'

shop/forms.py
from django import forms

from shop.models import Review


class AddReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['stars', 'text', 'image']
        widgets = {
            'stars': forms.Select(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

shop/views.py
# Встроенные модули
# import os
# from abc import ABC

# Внешние модули
from django.db.models import Avg, F, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Модули проекта
from shop.models import Product, Category, Review
from shop.forms import AddReviewForm


class ProductsHome(ListView):
    template_name = 'shop/products.html'
    context_object_name = 'products'
    paginate_by = 8

    def get_queryset(self):
        return Product.objects.all().annotate(
            sale=(F('price') - F('sale_price')) * 100 / F('price')
        )


class SearchProducts(ListView):
    model = Product
    template_name = 'shop/search_products.html'
    context_object_name = 'products'

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset = Product.objects.filter(Q(title__icontains=query)).annotate(
             sale=(F('price') - F('sale_price')) * 100 / F('price')
         )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['query'] = self.request.GET.get('q')
        return context


class ProductsInCategory(ListView):
    template_name = 'shop/single_category.html'
    context_object_name = 'products_in_cat'

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        return category.products.annotate(
            sale=(F('price') - F('sale_price')) * 100 / F('price')
        )
        # return Category.objects.select_related('category').get(
        #     slug=self.kwargs['category_slug']).annotate(
        #     sale=(F('price') - F('sale_price')) * 100 / F('price')
        # )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['products_in_cat']:
            first_prod, *_ = context['products_in_cat']
            category = first_prod.category
            context['category'] = category
            context['cat_selected'] = category.pk
            context['banners'] = category.banners.all()
            return context
        context['empty'] = 'В данной категории еще нет товаров...'
        return context


class ShowProductMixin(DetailView):
    model = Product
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context['product']
        context['reviews'] = product.reviews.all()
        if context['reviews']:
            avg_review_stars = product.reviews.aggregate(Avg("stars")).get('stars__avg', 0)
            context['avg_review_stars'] = round(avg_review_stars, 1)
        return context


class SingleProduct(ShowProductMixin):
    template_name = 'shop/single_product.html'


class AddReview(LoginRequiredMixin, ShowProductMixin, FormView):
    template_name = 'shop/add_review_for_product.html'
    form_class = AddReviewForm

    def get_success_url(self):
        return reverse_lazy(
            'shop:single_product',
            kwargs={"product_slug": self.kwargs.get('product_slug')}
        )

    def form_valid(self, form):
        form.instance.product_id = Product.objects.get(
            slug=self.kwargs.get('product_slug')).pk
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)


def page_404(request, exception):
    return render(
        request,
        'shop/404.html',
        status=404
    )

templates/shop/add_review_for_product.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Shop:{{ product.title }}{% endblock %}
{% block content %}
  <div class="container-fluid mt-5">
    <div class="row">
      <h3 class="text-center mx-5">{{ product.title }}</h3>
      <div class="col-md-4 mt-5">
        {% thumbnail product.image "500x500" as im %}
          <img class="card-img-top" src="{{ im.url }}">
        {% endthumbnail %}
      </div>
      <div class="col-md-6 mt-5">
        <h6 class="text-muted">{{ product.category }}</h6>
        <h6>
          <b>{{ product.price }} руб.</b>
        </h6>
        <p class="text-justify">{{ product.description }} руб.</p>
        {% if product.is_available %}
          <p class="mt-5">
            <small>В наличии</small>
          </p>
          <a href="" class="btn btn-primary">Купить</a>
        {% else %}
          <p class="text-danger mb-2 mt-5">
            <small>Недоступен к заказу</small>
          </p>
          <button class="btn btn-primary disabled">Купить</button>
        {% endif %}
      </div>
    </div>
    <div class="row mt-5">
      <hr>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a href="{% url 'shop:single_product' product.slug %}" class="nav-link">Все отзывы</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'shop:add_review' product.slug %}"
             class="nav-link active">Добавить отзыв</a>
        </li>
      </ul>
    </div>
    <div class="row mt-5">
      <div class="form-group">
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary mt-5">Отправить</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/shop/products.html
{% extends 'base.html' %}
{% block title %}Все товары{% endblock %}
{% block content %}
  <div class="row row-cols-xs-1 row-cols-sm-2 row-cols-md-4 g-4 mt-5">
    {% for product in products %}
      {% include 'includes/shop/product_card.html' %}
    {% endfor %}
  </div>
{% endblock %}
{% block pagination %}
  <nav aria-label="Навигация по страницам"
       class="container-fluid mt-5 mx-auto">
    <div class="d-lg-flex justify-content-center">
      <ul class="pagination">
        {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
            <li class="page-item active" aria-current="page">
              <a class="page-link">{{ p }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </nav>
{% endblock %}

templates/shop/search_products.html
{% extends 'base.html' %}
{% block title %}Результаты поиска товаров{% endblock %}
{% block content %}
  <p class="text-start mt-5">
    Результаты поиска "{{ query }}": Найдено <b>{{ products.count }}</b> товара(ов).
  </p>
  <div class="row row-cols-xs-1 row-cols-sm-2 row-cols-md-3 g-4">
    {% for product in products %}
      {% include 'includes/shop/product_card.html' %}
    {% endfor %}
  </div>
{% endblock %}

templates/shop/single_category.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Категории товаров: {{ category.title }}{% endblock %}
{% block content %}
  {% if category.banners.exists %}
    <div id="carouselExampleControls"
         class="carousel slide mt-3"
         data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for banner in banners %}
          <div class="carousel-item active">
            {% thumbnail banner.image "1900x339" crop="center" as im %}
              <img src="{{ im.url }}" class="d-block w-100" alt="slides">
            {% endthumbnail %}
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev"
              type="button"
              data-bs-target="#carouselExampleControls"
              data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Предыдущий</span>
      </button>
      <button class="carousel-control-next"
              type="button"
              data-bs-target="#carouselExampleControls"
              data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Следующий</span>
      </button>
    </div>
  {% endif %}
  {% if empty %}
    <h2 class="text-start mt-5">{{ empty }}</h2>
  {% else %}
    <div class="row row-cols-4 row-cols-md-4 g-4 mt-3">
      {% for product in products_in_cat.all %}
        {% include 'includes/shop/product_card.html' %}
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

templates/shop/single_product.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}Shop:{{ product.title }}{% endblock %}

{% block content %}
<div class="container-fluid mt-5">

    <div class="row">
        <h3 class="text-center mx-5">{{ product.title }}</h3>
        <div class="col-md-4 mt-5">
            {% thumbnail product.image "500x500" as im %}<img class="card-img-top" src="{{ im.url }}">
            {% endthumbnail %}
        </div>
        <div class="col-md-6 mt-5">
            {% if avg_review_stars is not None %}
                <p><img src="{% static 'images/star.png' %}" width="30" height="30">
                <b>{{ avg_review_stars }}</b></p>
            {% endif %}
            <h6 class="text-muted">{{ product.category }}</h6>
            <h6><b>{{ product.price }} руб.</b></h6>
            <p class="text-justify">{{ product.description }}</p>
            {% if product.is_available %}
              <p class="mt-5"><small>В наличии</small></p>
              <a href="" class="btn btn-primary">Купить</a>
            {% else %}
              <p class="text-danger mb-2 mt-5"><small>Недоступен к заказу</small></p>
              <button class="btn btn-primary disabled">Купить</button>
            {% endif %}
         </div>
    </div>

    <div class="row mt-5">
        <hr>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a href="{% url 'shop:single_product' product.slug %}" class="nav-link active">Все отзывы({{ product.reviews.count }})</a>
        </li>
       <li class="nav-item">
        <a href="{% url 'shop:add_review' product.slug %}" class="nav-link ">Добавить отзыв</a>
       </li>
      </ul>
    </div>
     <div class="row mt-5">
     {% for rev in reviews %}
         <div class="p-2 mb-1 bg-light text-dark "><small>{{rev.time_create}}</small></div>
         <p class="fw-bold">{{rev.author}}</p>
         <div class="badge bg-secondary text-wrap" style="width: 8rem;">
             Оценка товара - {{rev.stars}}
         </div>
         <p class="fs-6">{{rev.text}}</p>
         <hr>
     {% endfor %}
     </div>
</div>

{% endblock %}