shop/urls.py
from django.conf.urls.static import static
from django.urls import path

from wb_shop_root import settings
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductsHome.as_view(), name='index'),
    path('search', views.SearchProducts.as_view(), name='search_products'),
    path('<slug:product_slug>', views.SingleProduct.as_view(), name='single_product'),
    path('<slug:product_slug>/add_review', views.AddReview.as_view(), name='add_review'),
    path('categories/<slug:category_slug>', views.ProductsInCategory.as_view(), name='single_category')

]

# TODO: Перенести в urls.py -> wb_shop_root
handler404 = views.page_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register/success/', views.RegisterUser.as_view(), name='success'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html"),
        name="password_change_done",
       ),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

wb_shop_root/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    # TODO: Здесь лучше сделать так, чтобы в
    #  конце урла можно было не указывать слэш
    re_path(r'^admin/?', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/base.html
<!doctype html>
{% load static %}
{% load shop_tags %}
<html lang="en">
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>

<nav class="navbar navbar-dark bg-dark">
  <div>
    <a href="{% url 'shop:index' %}" class="nav-item mx-3"><img src="{% static 'images/logo1.png' %}" width="75"
                                                                height="75"></a>
    <a href="{% url 'shop:index' %}" class="navbar-brand mr-5">WB SHOP</a>
  </div>
  <div class="nav justify-content-end mx-5">
    {% if user.is_authenticated %}
     <div class="dropdown">
       <a class="nav-link dropdown-toggle me-2 text-bg-dark px-3" href="" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'images/user_profile.png' %}" width="50">
       </a>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        <li class="dropdown-item text-warning">{{ user.username }}</li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
        <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Сменить пароль</a></li>
        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти из профиля</a></li>
      </ul>
     </div>

    {% else %}
    <a href="{% url 'users:login' %}" class="navbar-brand mr-5">Войти</a>
    {% endif %}
    <form class="d-flex" method="get" action="{% url 'shop:search_products' %}">
      <input class="form-control me-2" type="search" required placeholder="Поиск" aria-label="Search" name="q">
      <button class="btn btn-outline-secondary" type="submit">Поиск</button>
    </form>
  </div>

</nav>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <aside class="bd-sidebar mt-4">
        <!-- Sidebar слева -->
        <h5>Категории</h5>
        {% get_categories as categories%}
        <hr>
        <ul class="list-group">
          {% for category in categories %}

          {% if category.id == cat_selected %}
          <li class="list-group-item active" aria-current="true">
            {{ category.title }}
          </li>
          {% else %}
          <li>
            <a href="{% url 'shop:single_category' category.slug %}" class="list-group-item list-group-item-action">
              {{ category.title }}
            </a>
          </li>
          {% endif %}

          {% endfor %}
        </ul>
      </aside>
    </div>
    <!-- Конец Sidebar'а -->

    <div class="col-md-9">
      <div class="container">
        {% block content %}
        {% endblock %}

      </div>
    </div>
  </div>
</div>
</body>
{% block pagination %}
{% endblock %}
<footer class="container-fluid">
  <div class="row">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-1 my-3 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">&copy; {% get_year %} WB SHOP</p>
    </footer>
  </div>
</footer>

</html>