shop/urls.py
from django.conf.urls.static import static
from django.urls import path

from wb_shop_root import settings
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductsHome.as_view(), name='index'),
    path('search', views.SearchProducts.as_view(), name='search_products'),
    path('<slug:product_slug>', views.SingleProduct.as_view(), name='single_product'),
    path('<slug:product_slug>/add_review', views.AddReview.as_view(), name='add_review'),
    path('categories/<slug:category_slug>', views.ProductsInCategory.as_view(), name='single_category')

]

# TODO: Перенести в urls.py -> wb_shop_root
handler404 = views.page_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register/success/', views.RegisterUser.as_view(), name='success'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html"),
        name="password_change_done",
       ),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

wb_shop_root/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    # TODO: Здесь лучше сделать так, чтобы в
    #  конце урла можно было не указывать слэш
    re_path(r'^admin/?', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    REQUIRED_FIELDS = ["email"]
    USERNAME_FIELD = 'phone_number'

    MALE_CHOICE = (
        ('Жен', 'Женский'),
        ('Муж', 'Мужской')
    )
    email = models.EmailField('Почтовый ящик', unique=True)
    date_birth = models.DateTimeField('Дата рождения', blank=True, null=True)
    male = models.CharField('Пол', choices=MALE_CHOICE, max_length=7)
    phone_number = models.CharField(
        'Телефонный номер',
        max_length=12,
        validators=[RegexValidator(
            regex=r'^\+?1?\d{11,11}$',
            message="Номер телефона должен быть введен в формате: '+79999999999'")],
        unique=True,

    )

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.views import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from shop.templatetags.shop_tags import get_year


class MyLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Телефон', widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    password = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):

    password1 = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )
    password2 = forms.CharField(
        label='Подтверждение пароля', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = get_user_model()
        fields = [
            'username', 'email', 'phone_number',
            'male', 'date_birth', 'first_name',
            'last_name', 'password1'
        ]

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@mail.ru'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '+7900000000'
            }),
            'male': forms.Select(attrs={'class': 'form-control'}),
            'date_birth': forms.SelectDateWidget(
                attrs={'class': 'form-control'},
                years=tuple(range(get_year()-100, get_year()-16))
            ),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].help_text = "Формат номера '+79999999999'"


class ProfileUserForm(forms.ModelForm):
    phone_number = username = forms.CharField(
        disabled=True,
        label='Телефон',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    username = forms.CharField(
        disabled=True,
        label='Логин',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = get_user_model()
        fields = [
            'username', 'email', 'phone_number',
            'male', 'date_birth', 'first_name',
            'last_name'
        ]
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@mail.ru'
            }),
            'male': forms.Select(attrs={'class': 'form-control'}),
            'date_birth': forms.SelectDateWidget(
                attrs={'class': 'form-control'},
                years=tuple(range(get_year() - 100, get_year() - 16))
            ),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Старый пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )
    new_password1 = forms.CharField(
        label='Новый пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )
    new_password2 = forms.CharField(
        label='Подтверждения пароля', widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )

users/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from users.forms import MyLoginForm, RegisterForm, ProfileUserForm, PasswordChangeForm
from django.views.generic import CreateView, UpdateView, View
from django.http import HttpResponse
from django.contrib.messages.views import SuccessMessageMixin


class LoginUser(LoginView):
    form_class = MyLoginForm
    template_name = 'users/login.html'


class RegisterUser(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = 'success'
    success_message = "Пользователь с логином '%(username)s' успешно создан."


class ProfileUser(UpdateView):
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход в Личный кабинет{% endblock %}
{% block content %}
<div class="row mt-5">
    <div class="col-md-9 col-sm-auto col-lg-6">

<h4>Авторизация</h4>

    <form class="mt-5" method="POST" >
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        {{ form.as_p }}
        <p class="align-middle">
            <button type="submit" class="btn btn-primary ">Войти</button>
        </p>
    </form>

    <table class="table">
     <tbody>
        <tr>
          <td><a class="pr-5" href="{% url 'users:password_reset' %}" >Забыли пароль?</a></td>
          <td><a class="mt-5" href="{% url 'users:register' %}" >Еще не зарегистрированы?</a></td>
        </tr>
     </tbody>
    </table>

    </div>
</div>

{% endblock %}

templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Пароль изменен{% endblock %}

{% block content %}
<div class="row mt-5">
<h4>Пароль успешно изменен!</h4>


<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}
</div>

templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}Изменение пароля{% endblock %}

{% block content %}
<div class="row mt-5">
<h4>Изменение пароля</h4>
<div class="row mt-5">

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit" class="btn btn-primary ">Изменить пароль</button>
</form>
    </div>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Редактирование профиля{% endblock %}
{% block content %}

<div class="row mt-3">
<h4>Редактирование профиля</h4>
<div class="row mt-3">
   <div class="col-md-9 col-sm-auto col-lg-6">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}

            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
             <div class="form-error text-danger fst-italic"><small>{{ f.errors }}</small></div>

            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3">Сохранить изменения</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}
{% block content %}

{% if messages %}

<div class="row mt-5">
    <p>Поздравляем вы зарегистрировались!</p>
    <p>{{ messages }}</p>
    <p>Перейти на страницу <a href="{% url 'users:login' %}">авторизации</a></p>
</div>

{% else %}
    <div class="row mt-5">
    <h4>Регистрация</h4>
    <div class="row mt-5">
        <div class="col-md-9 col-sm-auto col-lg-6">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}

                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                 <div class="form-error text-danger fst-italic"><small>{{ f.errors }}</small></div>

                {% endfor %}
                <button type="submit" class="btn btn-primary mt-5">Зарегистрироваться</button>
            </form>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}